version: '3'
## build:
# context: .
# dockerfile: Dockerfile.dev
services:
  web:
    container_name: ng-cash-frontend
    image: node:18-alpine3.15
    restart: 'always'
    build: .
    tty: true
    volumes:
      - ./:/src/app
    ports:
      - 5173:5173
      - 5174:5174
networks:
  default:
    external:
      name: ng-cash-network
